title: specron
heading: a lightweight, open source and magic-free framework for testing Solidity smart contracts.
logo: /assets/images/specron.svg
email: info@specron.org
google_analytics: 

menu:
  - url: '#specron-framework'
    title: What is Specron
  - url: '#installation'
    title: Getting started 

remote_theme: specron/gp-theme
plugins:
  - jekyll-remote-theme
